export default {
  name: 'factory',
  title: 'Factories',
  type: 'document',
  groups: [
    { name: 'info', title: 'المعلومات الأساسية', default: true },
    { name: 'contact', title: 'معلومات التواصل' },
    { name: 'training', title: 'التدريب' },
    { name: 'media', title: 'الصور' },
  ],
  fields: [
    {
      name: 'name',
      title: 'اسم المصنع',
      type: 'string',
      group: 'info',
      validation: Rule => Rule.required(),
    },
    {
      name: 'slug',
      title: 'الرابط',
      type: 'slug',
      group: 'info',
      options: { source: 'name', maxLength: 96 },
      validation: Rule => Rule.required(),
    },
    {
      name: 'shortDescription',
      title: 'وصف مختصر',
      description: 'يظهر في بطاقة المصنع ونتائج البحث',
      type: 'string',
      group: 'info',
      validation: Rule => Rule.max(160),
    },
    {
      name: 'description',
      title: 'الوصف الكامل',
      description: 'يظهر في صفحة المصنع التفصيلية',
      type: 'text',
      group: 'info',
      rows: 4,
    },
    {
      name: 'location',
      title: 'الموقع',
      type: 'string',
      group: 'info',
    },
    {
      name: 'logo',
      title: 'شعار المصنع',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
    },
    {
      name: 'coverImage',
      title: 'صورة الغلاف',
      description: 'تظهر في أعلى صفحة المصنع (اختياري)',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
      fields: [
        {
          name: 'alt',
          title: 'نص بديل',
          type: 'string',
        },
      ],
    },
    {
      name: 'phone',
      title: 'رقم الهاتف',
      type: 'string',
      group: 'contact',
    },
    {
      name: 'email',
      title: 'البريد الإلكتروني',
      type: 'string',
      group: 'contact',
      validation: Rule => Rule.email(),
    },
    {
      name: 'website',
      title: 'الموقع الإلكتروني',
      description: 'رابط موقع المắn أو صفحته على وسائل التواصل',
      type: 'url',
      group: 'contact',
    },
    {
      name: 'contact',
      title: 'رقم للتواصل (مختصر)',
      description: 'يظهر بجانب زر الاتصال',
      type: 'string',
      group: 'contact',
    },
    {
      name: 'hours',
      title: 'ساعات التدريب',
      type: 'number',
      group: 'training',
      validation: Rule => Rule.min(0),
    },
    {
      name: 'departments',
      title: 'الأقسام المتاحة',
      type: 'array',
      group: 'training',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'تكنولوجيا المعلومات', value: 'تكنولوجيا المعلومات' },
          { title: 'تكنولوجيا الشبكات', value: 'تكنولوجيا الشبكات' },
          { title: 'تكنولوجيا الأجهزة', value: 'تكنولوجيا الأجهزة' },
          { title: 'تصنيع غذائي', value: 'تصنيع غذائي' },
        ],
      },
    },
    {
      name: 'price',
      title: 'المكافأة / التكلفة',
      type: 'string',
      group: 'training',
    },
    {
      name: 'rating',
      title: 'التقييم',
      description: 'تقييم المصنع من 0 إلى 5',
      type: 'number',
      group: 'info',
      validation: Rule => Rule.min(0).max(5),
    },
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'location',
      media: 'logo',
    },
  },
}
