export default {
  name: 'internship',
  title: 'Internship Opportunities',
  type: 'document',
  groups: [
    { name: 'info', title: 'المعلومات الأساسية', default: true },
    { name: 'details', title: 'تفاصيل التدريب' },
    { name: 'contact', title: 'التواصل والتقديم' },
    { name: 'media', title: 'الصور' },
  ],
  fields: [
    {
      name: 'title',
      title: 'عنوان الفرصة',
      type: 'string',
      group: 'info',
      validation: Rule => Rule.required(),
    },
    {
      name: 'slug',
      title: 'الرابط',
      type: 'slug',
      group: 'info',
      options: { source: 'title', maxLength: 96 },
      validation: Rule => Rule.required(),
    },
    {
      name: 'factory',
      title: 'المصنع / الشركة',
      type: 'reference',
      to: [{ type: 'factory' }],
      group: 'info',
    },
    {
      name: 'location',
      title: 'الموقع',
      type: 'string',
      group: 'info',
    },
    {
      name: 'description',
      title: 'الوصف الكامل',
      type: 'text',
      group: 'info',
      rows: 6,
    },
    {
      name: 'shortDescription',
      title: 'وصف مختصر',
      description: 'يظهر في بطاقة الفرصة',
      type: 'string',
      group: 'info',
      validation: Rule => Rule.max(200),
    },
    {
      name: 'hours',
      title: 'ساعات التدريب',
      type: 'number',
      group: 'details',
      validation: Rule => Rule.min(0),
    },
    {
      name: 'duration',
      title: 'المدة',
      description: 'مثال: 3 أشهر، 8 أسابيع',
      type: 'string',
      group: 'details',
    },
    {
      name: 'price',
      title: 'المكافأة / التكلفة',
      type: 'string',
      group: 'details',
    },
    {
      name: 'departments',
      title: 'الأقسام المناسبة',
      type: 'array',
      group: 'details',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'تكنولوجيا المعلومات', value: 'تكنولوجيا المعلومات' },
          { title: 'تكنولوجيا الشبكات', value: 'تكنولوجيا الشبكات' },
          { title: 'تكنولوجيا الأجهزة', value: 'تكنولوجيا الأجهزة' },
          { title: 'تصنيع غذائي', value: 'تصنيع غذائي' },
        ],
      },
    },
    {
      name: 'academicYears',
      title: 'الفرق الدراسية المناسبة',
      type: 'array',
      group: 'details',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'الأولى', value: 'الأولى' },
          { title: 'الثانية', value: 'الثانية' },
          { title: 'الثالثة', value: 'الثالثة' },
          { title: 'الرابعة', value: 'الرابعة' },
        ],
      },
    },
    {
      name: 'applyUrl',
      title: 'رابط التقديم',
      description: 'رابط صفحة التقديم أو النموذج الإلكتروني',
      type: 'url',
      group: 'contact',
      validation: Rule => Rule.uri({ scheme: ['http', 'https'] }),
    },
    {
      name: 'contactEmail',
      title: 'بريد التواصل',
      type: 'string',
      group: 'contact',
      validation: Rule => Rule.email(),
    },
    {
      name: 'contactPhone',
      title: 'هاتف التواصل',
      type: 'string',
      group: 'contact',
    },
    {
      name: 'image',
      title: 'الصورة',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
      fields: [
        {
          name: 'alt',
          title: 'نص بديل',
          type: 'string',
        },
      ],
    },
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'factory.name',
      media: 'image',
    },
  },
}
